---
# Stash administrator
admin_user: admin    
admin_password: password 
admin_name: Stash admin(automatic)
admin_email: admin_email@yourcompany.com

# Stash regular user(for pushing code)
stash_user: user1
stash_password: password
stash_name: User number one
stash_email: user_email@yourcompany.com

# Stash settings
system_name: Stash_sytem_1

# Project and repository information
proj_key: PJ1
proj_name: Project 1
proj_desc: An automatically created project
repo_name: repository_1

# Database parameters
db_user: postgres
db_password: password
db_type: postgresql
db_container: postgres
db_port: 5432
db_name: stash
db_driver: org.postgresql.Driver

# Stash cloning parameters
license: your_license_number_here
server_id: your_server_id_here

# Proxy
proxy: your_proxy_here
...
